# Вводная информация по структуре курса

| | |
|:--|:--|
| **Дисциплина** | *Алгоритмизация и программирование в решении задач разработки* |
| **Лектор** | *Уразов Эльдар Валентинович*, начальник отдела цифровизации объектов разработки, tg:@lurazov |
| **Дата** | *2026-02-10* |

## План курса

**Цель курса:** разработка упрощённого симулятора газового месторождения с основными компонентами — от модели пласта до выхода из системы компримирования.

В ходе курса мы последовательно построим каждый элемент производственной цепочки газодобычи и объединим их в единую интегрированную модель.

---

**1. Настройка рабочего окружения и входная диагностика навыков программирования**

**2. Основные объекты и модели газового промысла. Физико-химические свойства пластовых флюидов: законы, модели и допущения**


**3. Модель пласта-коллектора: материальный баланс и уравнение пьезопроводности**


**4. Модель скважины: уравнение притока, закон Дарси и его аппроксимации**


**5. Модель скважины: потери давления при движении флюида по стволу**


**6. Гидравлическая модель трубопроводного транспорта**


**7. Модель системы промысловой подготовки газа**


**8. Модель системы компримирования**


**9. Интегрированная модель газового месторождения: сборка и валидация**


## Результаты обучения

По завершении курса вы будете обладать **междисциплинарной экспертизой**, объединяющей три ключевых направления:

---

**Физика процессов газодобычи**

Вы сформируете целостное представление о физических явлениях, протекающих на каждом участке производственной цепочки — от фильтрации газа в пористой среде пласта до термодинамики компримирования. Это не набор разрозненных формул, а системное понимание причинно-следственных связей между компонентами месторождения.

**Математический аппарат и принципы моделирования**

Вы освоите базовые подходы к построению инженерных моделей: формулировку допущений, выбор уравнений, численные методы решения и верификацию результатов. Вы будете понимать, как упрощённая математическая модель отражает реальный физический процесс, где проходят границы её применимости и как её калибровать по фактическим данным.

**Прикладные навыки программирования**

Вы приобретёте практический опыт разработки вычислительного программного продукта — от архитектуры и реализации отдельных модулей до их интеграции в единую систему. Итогом курса станет полноценный пет-проект: работающий симулятор газового месторождения, который вы сможете включить в своё портфолио.

---

> Главная ценность курса — не каждый навык по отдельности, а умение связать физику, математику и код в единый инженерный инструмент. Именно эта способность отличает специалиста, который понимает *как работает модель*, от того, кто просто использует чужое программное обеспечение.

---

## Часть 1. Настройка программного окружения

В этом разделе мы пошагово настроим всё необходимое для работы на протяжении курса: создадим проект, развернём виртуальную среду Python, установим Jupyter Notebook и инициализируем репозиторий Git.

### 1.1. Создание папки проекта

Создайте папку, в которой будет храниться весь код курса, и перейдите в неё:

```bash
mkdir gas_field_simulator
cd gas_field_simulator
```

> **Рекомендация:** выберите удобное расположение (например, `Desktop` или `Documents`). Избегайте путей с кириллицей и пробелами — это может вызвать проблемы с некоторыми инструментами.

### 1.2. Создание виртуальной среды

Виртуальная среда изолирует зависимости проекта от глобальной установки Python. Это позволяет каждому проекту иметь собственный набор библиотек нужных версий.

```bash
python -m venv .venv
```

Эта команда создаст папку `.venv` внутри вашего проекта со всей необходимой инфраструктурой.

### 1.3. Активация и деактивация виртуальной среды

**Активация** — подключает среду к текущей сессии терминала. После активации все команды `pip` и `python` будут работать внутри этой среды.

| Платформа | Команда активации |
|:--|:--|
| **Windows (PowerShell)** | `.venv\Scripts\Activate.ps1` |
| **Windows (cmd)** | `.venv\Scripts\activate.bat` |
| **Linux / macOS** | `source .venv/bin/activate` |

После активации в начале строки терминала появится `(.venv)` — это индикатор того, что среда активна.

**Деактивация** — возврат к глобальному Python:

```bash
deactivate
```

> **Важно:** активируйте виртуальную среду каждый раз перед началом работы с проектом.

### 1.4. Установка библиотек

Убедитесь, что виртуальная среда активирована, и установите необходимые пакеты:

```bash
pip install numpy pandas matplotlib
```

Полезные команды для управления пакетами:

```bash
# Просмотр установленных пакетов
pip list

# Сохранение зависимостей в файл (для воспроизводимости)
pip freeze > requirements.txt

# Установка зависимостей из файла (на другой машине)
pip install -r requirements.txt
```

### 1.5. Установка и запуск Jupyter Notebook

Установите Jupyter Notebook (классический, не JupyterLab):

```bash
pip install notebook
```

Для запуска выполните команду из корневой папки проекта:

```bash
jupyter notebook
```

В браузере автоматически откроется интерфейс Jupyter с файловой системой вашего проекта.

#### Основные элементы интерфейса Jupyter Notebook

- **Dashboard (панель управления)** — файловый менеджер; здесь вы создаёте и открываете ноутбуки.
- **Ячейки (Cells)** — основные блоки ноутбука. Бывают двух типов:
  - `Code` — для исполняемого Python-кода.
  - `Markdown` — для форматированного текста, формул, заголовков.
- **Ядро (Kernel)** — процесс Python, выполняющий код. Управление: `Kernel → Restart`, `Kernel → Restart & Run All`.
- **Режимы работы:**
  - *Command mode* (синяя рамка) — навигация между ячейками (`↑`/`↓`, `A`/`B` — вставить ячейку, `DD` — удалить).
  - *Edit mode* (зелёная рамка) — редактирование содержимого ячейки.
  - Переключение: `Enter` (в edit), `Esc` (в command).

#### Горячие клавиши (Command mode)

| Клавиша | Действие |
|:--|:--|
| `Shift + Enter` | Выполнить ячейку и перейти к следующей |
| `Ctrl + Enter` | Выполнить ячейку без перехода |
| `A` | Вставить ячейку выше |
| `B` | Вставить ячейку ниже |
| `DD` | Удалить ячейку |
| `M` | Переключить ячейку в Markdown |
| `Y` | Переключить ячейку в Code |
| `H` | Показать все горячие клавиши |

### 1.6. Инициализация репозитория Git

Git — система контроля версий, которая позволяет отслеживать изменения в коде, возвращаться к предыдущим версиям и совместно работать над проектом.

#### Первоначальная настройка (выполняется один раз)

```bash
git config --global user.name "Ваше Имя"
git config --global user.email "your.email@example.com"
```

#### Инициализация репозитория

```bash
git init
```

#### Основные команды

```bash
# Проверить статус репозитория
git status

# Добавить файлы в индекс (staging area)
git add .                    # все файлы
git add filename.py          # конкретный файл

# Зафиксировать изменения (commit)
git commit -m "Описание изменений"

# Просмотреть историю коммитов
git log
git log --oneline            # краткий формат
```

#### Подключение удалённого репозитория и отправка кода

```bash
# Добавить удалённый репозиторий (GitHub, GitLab и т.д.)
git remote add origin https://github.com/username/repository.git

# Отправить коммиты на сервер
git push -u origin main
```

> **Совет:** делайте коммиты часто и с осмысленными сообщениями. Каждый коммит — это «точка сохранения» вашего проекта.

### 1.7. Файл .gitignore

Файл `.gitignore` указывает Git, какие файлы и папки **не нужно** отслеживать. Создайте файл `.gitignore` в корне проекта со следующим содержимым:

```
# Виртуальная среда
.venv/

# Кэш Python
__pycache__/
*.pyc
*.pyo

# Jupyter Notebook
.ipynb_checkpoints/

# Системные файлы
.DS_Store
Thumbs.db

# IDE
.vscode/
.idea/
```

Добавьте `.gitignore` в репозиторий:

```bash
git add .gitignore
git commit -m "Добавлен .gitignore"
```

> **Важно:** `.gitignore` следует создать **до первого коммита** с кодом, чтобы служебные файлы не попали в историю.

---

## Часть 2. Входное тестирование по Python

Цель тестирования — оценить текущий уровень владения языком Python. Результаты помогут адаптировать темп и глубину изложения материала.

**Время выполнения:** ~45 минут

**Формат:** задачи с написанием кода и вопросы с вариантами ответов.

**Правила:**
- Пишите код в предоставленных ячейках.
- Для квизов укажите букву ответа в ячейке ниже.
- Можно запускать ячейки для проверки.
- Не используйте внешние источники.

### Уровень 1. Базовый синтаксис

**Задание 1. Переменные и типы данных**

1. Создайте переменные: `a` (целое число `42`), `b` (дробное число `3.14`), `c` (строка `"Python"`), `d` (логическое значение `True`).
2. Преобразуйте строку `"2.718"` в число с плавающей точкой и сохраните в переменную `e`.
3. Преобразуйте переменную `b` в целое число и сохраните в переменную `f`.
4. Выведите каждую переменную и её тип в формате: `значение -> тип`.

*Ожидаемый вывод (пример для первой строки):* `42 -> <class 'int'>`

In [2]:
# Задание 1

# 1.1
# в python типизация по принципу duck typing поэтому не обязательно указывать тип
a = int(42)
b = float(3.14)
c = str('Python')
d = bool(True)

# 1.2
stroka = '2.718'
e = float(stroka)

# 1.3
f = int(b)

# 1.4
my_list = [a,b,c,d,e,f]

for i in my_list:
    print(f'{i} -> {type(i)}')


42 -> <class 'int'>
3.14 -> <class 'float'>
Python -> <class 'str'>
True -> <class 'bool'>
2.718 -> <class 'float'>
3 -> <class 'int'>


**Задание 2. Арифметические и логические операции**

Даны переменные `a = 17` и `b = 5`. Вычислите и выведите:

1. Результат целочисленного деления `a` на `b`.
2. Остаток от деления `a` на `b`.
3. `b` в третьей степени.
4. Логическое выражение: «`a` больше 10 **И** `b` меньше 10 **ИЛИ НЕ** (`a` равно `b`)».
5. Арифметическое выражение: произведение `a` и `b`, плюс `b` в квадрате, минус результат целочисленного деления `a` на `b`.

In [3]:
# Задание 2
a = 17
b = 5

# 2.1
print(a//b)

# 2.2
print(a%b)

# 2.3
print(b**3)

# 2.4
print(a > 10 & (b<10 | a!=b))

# 2.5
print(a*b+b**2-a//b)


3
2
125
True
107


**Задание 3. Условные конструкции**

Напишите код, который по значению переменной `score` (целое число от 0 до 100) выводит буквенную оценку:

| Диапазон | Оценка |
|:--|:--|
| 90–100 | A |
| 75–89 | B |
| 60–74 | C |
| 40–59 | D |
| 0–39 | F |

Проверьте ваш код для значений `score = 85`, `score = 42`, `score = 91`.

In [4]:
# Задание 3
score = 90
if score <= 100 and score >= 0 and (type(score) == float or type(score) == int):
    print('Corret')
    if score >= 90:
        print('A')
    elif score >= 75:
        print('B')
    elif score >= 60:
        print('C')
    elif score >= 40:
        print('D')
    else:
        print('F')
else:
    print('incorrect')


Corret
A


**Задание 4. Циклы**

Дан список чисел:

```python
numbers = [12, -7, 3, -2, 15, 0, 8, -1, 6, 10, -5, 4]
```

Напишите цикл, который обходит список и подсчитывает количество положительных чётных чисел, при этом:
1. Отрицательные числа должны пропускаться без дальнейшей обработки.
2. Если встретится число, превышающее 14, обход списка должен прекратиться досрочно.
3. Выведите итоговый счётчик.

In [5]:
# Задание 4
numbers = [12, -7, 3, -2, 15, 0, 8, -1, 6, 10, -5, 4]
counter = 0

for i in numbers:
    if i > 14:
        break
    if i < 0:
        continue
    if i%2 == 0:
        counter += 1

print(counter)
    

1


**Квиз 5. Что выведет следующий код?**

```python
result = []
for i in range(5):
    if i == 3:
        break
    result.append(i * 2)
print(result)
```

Варианты ответа:
- **A)** `[0, 2, 4]`
- **B)** `[0, 2, 4, 6]`
- **C)** `[0, 2, 4, 6, 8]`
- **D)** `[2, 4, 6]`

**Ваш ответ:** B # range(5) создаёт список [0,1,2,3,4]

### Уровень 2. Структуры данных

**Задание 6. Списки и list comprehension**

1. Дан список чисел от 1 до 20. С помощью **list comprehension** создайте новый список, содержащий квадраты только тех чисел, которые делятся на 3.
2. Дан список строк:
```python
words = ["hello", "world", "python", "is", "great"]
```
Получите срез с 2-го по 4-й элемент (включительно). Разверните этот срез в обратном порядке.

In [6]:
# Задание 6
numbers = list(range(1, 21))
words = ["hello", "world", "python", "is", "great"]

# 6.1
new_list = [i**2 for i in numbers if i%3==0]
print(new_list)

# 6.2
print(words[1:3][::-1])


[9, 36, 81, 144, 225, 324]
['python', 'world']


**Задание 7. Словари**

Дан список кортежей с данными о студентах (имя, город):

```python
students = [
    ("Алексей", "Москва"),
    ("Мария", "Казань"),
    ("Иван", "Москва"),
    ("Елена", "Казань"),
    ("Дмитрий", "Новосибирск"),
    ("Ольга", "Москва"),
]
```

Создайте словарь, в котором ключ — город, значение — список имён студентов из этого города. Выведите результат.

*Подсказка о формате:* для ключа `"Москва"` значением будет список из трёх имён.

In [7]:
# Задание 7
students = [
    ("Алексей", "Москва"),
    ("Мария", "Казань"),
    ("Иван", "Москва"),
    ("Елена", "Казань"),
    ("Дмитрий", "Новосибирск"),
    ("Ольга", "Москва"),
]

city_dict = dict()
for name, city in students:
    if not(city in city_dict):
        city_dict[city] = []

    city_dict[city].append(name)

print(city_dict)


{'Москва': ['Алексей', 'Иван', 'Ольга'], 'Казань': ['Мария', 'Елена'], 'Новосибирск': ['Дмитрий']}


**Задание 8. Множества**

Даны два списка:

```python
list_a = [1, 2, 3, 4, 5, 6, 7, 8]
list_b = [5, 6, 7, 8, 9, 10, 11, 12]
```

Используя **множества**, найдите и выведите:
1. Общие элементы обоих списков (пересечение).
2. Элементы, которые есть в `list_a`, но отсутствуют в `list_b` (разность).
3. Все уникальные элементы из обоих списков (объединение).
4. Элементы, которые есть только в одном из списков (симметрическая разность).

In [8]:
# Задание 8
list_a = [1, 2, 3, 4, 5, 6, 7, 8]
list_b = [5, 6, 7, 8, 9, 10, 11, 12]

# 8.1
print(set(list_a)&set(list_b))

# 8.2
print(set(list_a)-set(list_b))

# 8.3
print(set(list_a)|set(list_b))

# 8.4
print(set(list_a)^set(list_b))

{8, 5, 6, 7}
{1, 2, 3, 4}
{1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12}
{1, 2, 3, 4, 9, 10, 11, 12}


**Квиз 9. Мутабельность и поведение ссылок**

Что выведет следующий код?

```python
def add_item(lst=[]):
    lst.append(1)
    return lst

print(add_item())
print(add_item())
print(add_item())
```

Варианты ответа:
- **A)** `[1]`, `[1]`, `[1]`
- **B)** `[1]`, `[1, 1]`, `[1, 1, 1]`
- **C)** `[]`, `[1]`, `[1, 1]`
- **D)** Ошибка выполнения

**Ваш ответ:** B # из интернета, не знал об этой особенности вызова функции

### Уровень 3. Функции

**Задание 10. Функция с параметрами по умолчанию**

Напишите функцию `format_name`, которая принимает имя, фамилию, необязательное отчество и необязательный флаг обратного порядка.

Поведение:
- По умолчанию: `"Имя Фамилия"` или `"Имя Отчество Фамилия"`.
- При обратном порядке: `"Фамилия, Имя"` или `"Фамилия, Имя Отчество"`.

*Пример:* `format_name("Иван", "Петров")` → `"Иван Петров"`

In [9]:
# Задание 10
def format_name(name, lastname, surname=[], revers=[]):
    
    # Проверка на отчество
    if surname == []:
        Name_surname = name
    else:
        Name_surname = name +' '+ surname
    
    # Проверка на ревёрс
    if revers == []:
        fullname = Name_surname + ' ' + lastname
    else:
        fullname = lastname + ', ' + Name_surname
 
    return fullname


fullname = format_name('Yura','Fedoreev','Georgievich')

print(fullname)


Yura Georgievich Fedoreev


**Задание 11. Функция с произвольным числом аргументов**

Напишите функцию `make_tag`, которая формирует строку HTML-тега:

- Принимает имя тега (обязательный аргумент).
- Принимает произвольное количество строк содержимого (объединяются через пробел).
- Принимает произвольное количество именованных атрибутов.

> Подсказка: символ `_` в конце имени атрибута (например, `class_`) следует убрать при формировании строки.

*Пример:* `make_tag("p", "Hello!")` → `"<p>Hello!</p>"`

In [25]:
# Задание 11

# Создание кортэжа с использованием * пришлось повторить

def make_tag(tag, *text):
    text = ' '.join(text)  
    new_tag = f'<{tag}>{text}</{tag}>'

    return new_tag

new_tag = make_tag('p','Hellow', 'new', 'world')
print(new_tag)

<p>Hellow new world</p>


**Задание 12. Lambda-функции и функциональный стиль**

Дан список строк:

```python
words = ["программирование", "газ", "пласт", "скважина", "нефть", "компримирование", "Python", "моделирование"]
```

Используя **lambda-функции** и встроенные функции Python:
1. Получите новый список, отсортированный по длине строки (по возрастанию).
2. Получите список, содержащий только строки длиной больше 5 символов.
3. Получите список, в котором все строки переведены в верхний регистр.

Выведите результат каждой операции.

In [11]:
# Задание 12
words = ["программирование", "газ", "пласт", "скважина", "нефть", "компримирование", "Python", "моделирование"]

# Пришлось повторить использование lambda функции с прошлого курса :)

# 12.1
sort_words = sorted(words, key=len)
print(sort_words)

# 12.2
lambda_words = list(filter(lambda i: len(i) > 5, sort_words))
print(lambda_words)

# 12.3
upper_words = list(map(lambda i: i.upper(), lambda_words))
print(upper_words)


['газ', 'пласт', 'нефть', 'Python', 'скважина', 'моделирование', 'компримирование', 'программирование']
['Python', 'скважина', 'моделирование', 'компримирование', 'программирование']
['PYTHON', 'СКВАЖИНА', 'МОДЕЛИРОВАНИЕ', 'КОМПРИМИРОВАНИЕ', 'ПРОГРАММИРОВАНИЕ']


**Задание 13. Рекурсия**

1. Напишите **рекурсивную** функцию `fibonacci(n)`, которая возвращает n-е число Фибоначчи (0, 1, 1, 2, 3, 5, 8, ...).
2. Попробуйте вызвать её для `n = 35`. Обратите внимание на время выполнения.
3. Напишите улучшенную версию с **кэшированием** промежуточных результатов, устраняющую повторные вычисления.
4. Сравните скорость работы обеих версий.

In [12]:
# Задание 13
def fibonacci(n):
    if n <= 0:
        return 0
    elif n == 1:
        return 1
    else:
        return fibonacci(n - 1) + fibonacci(n - 2)

print(fibonacci(35))

# не помню как делать с кэшированием

9227465


**Квиз 14. Область видимости переменных**

Что выведет следующий код?

```python
x = 10

def outer():
    x = 20
    def inner():
        nonlocal x
        x = 30
    inner()
    print("outer:", x)

outer()
print("global:", x)
```

Варианты ответа:
- **A)** `outer: 30`, `global: 10`
- **B)** `outer: 30`, `global: 30`
- **C)** `outer: 20`, `global: 10`
- **D)** `outer: 20`, `global: 20`

**Ваш ответ:** A

### Уровень 4. Объектно-ориентированное программирование

**Задание 15. Создание класса**

Создайте класс `BankAccount`, описывающий банковский счёт:

- При создании указывается имя владельца и начальный баланс (по умолчанию 0).
- Должна быть возможность пополнить счёт (только положительной суммой).
- Должна быть возможность снять средства (только если на счёте достаточно средств).
- Должен быть метод, возвращающий информацию о счёте в виде строки.

Создайте экземпляр, выполните несколько операций и выведите информацию.

In [13]:
# Задание 15

# --- Для решения задач на ООП, пришлось повторять пройденный материал с прошлого курса

class BankAccount:
    def __init__(self, user, balance=0):
        self.user = user
        self.balance = balance

    # Пополнение счёта
    def deposit(self, Money):
        if Money <= 0:
            self.balance += 0
        else:
            self.balance += abs(Money)

    # Снятие средств
    def withdraw(self, Money):
        Money = abs(Money)
        if Money > self.balance:
            return print('Not enough money')
        self.balance -= Money

    # Информация о счёте
    def get_balance(self):
        balance = self.balance
        return f'balance = {balance}'
    
account = BankAccount('Yura Fedoreev', 1000)
account.balance
account.user
account.deposit(0)
account.withdraw(5500)
account.get_balance()


Not enough money


'balance = 1000'

**Задание 16. Наследование**

Создайте класс `SavingsAccount`, наследующий от `BankAccount`:

- Счёт имеет процентную ставку (например, 5% годовых).
- Должен быть метод начисления процентов, увеличивающий баланс в соответствии со ставкой.
- Информация о счёте должна дополнительно отображать процентную ставку.

Создайте экземпляр, внесите депозит, начислите проценты, выведите информацию.

In [14]:
# Задание 16

# --- Для решения задач на ООП, пришлось повторять пройденный материал с прошлого курса

class SavingsAccount(BankAccount):
    def __init__(self, user, balance=0, interest_rate=0.05):
        super().__init__(user, balance)
        self.interest_rate = interest_rate

    # Начисление процентов
    def add_interest(self):
        self.balance += self.balance * self.interest_rate

savings_account = SavingsAccount('Yura Fedoreev', 1000, 0.05)
savings_account.deposit(500) # Пополнение счёта

print(savings_account.get_balance(), 'Before')
savings_account.add_interest()
print(savings_account.get_balance(), 'After')

savings_account.withdraw(50)


balance = 1500 Before
balance = 1575.0 After


**Задание 17. Перегрузка операторов**

Создайте класс `Vector2D` для представления двумерного вектора (x, y). Реализуйте поддержку следующих операций:

- Сложение и вычитание двух векторов через операторы `+` и `-`.
- Умножение вектора на число (скаляр) через оператор `*`.
- Вычисление длины (модуля) вектора через встроенную функцию `abs()`.
- Строковое представление, например `"Vector2D(3, 4)"`.
- Сравнение двух векторов через `==`.

Продемонстрируйте работу всех операций.

In [15]:
# Задание 17

# --- Для решения задач на ООП, пришлось повторять пройденный материал с прошлого курса

class Vector2D():
    def __init__(self, x, y):
        self.x = x
        self.y = y
        
    def calculate(self, match, vector=[]):
        if match == '+':
            return self.x + vector[0], self.y + vector[1]
        elif match == '-':
            return self.x - vector[0], self.y - vector[1]
        elif match == '*':
            return self.x * sum(vector), self.y * sum(vector)
        elif match == 'abs':
            return (abs(self.x), abs(self.y))
        elif match == 'str':
            return f'Vector2D({self.x}, {self.y})'
        elif match == '==':
            return self.x == vector[0] and self.y == vector[1]
        else:
            return 'Not correct'
        
list_operations = ['+', '-', '*', 'abs', 'str', '==']
vector1 = Vector2D(3, 4)
for i in list_operations:
    print(vector1.calculate(i, [1, 2]))

(4, 6)
(2, 2)
(9, 12)
(3, 4)
Vector2D(3, 4)
False


**Квиз 18. Порядок разрешения методов (MRO)**

Что выведет следующий код?

```python
class A:
    def method(self):
        return "A"

class B(A):
    pass

class C(A):
    def method(self):
        return "C"

class D(B, C):
    pass

print(D().method())
```

Варианты ответа:
- **A)** `"A"`
- **B)** `"C"`
- **C)** `"B"`
- **D)** Ошибка выполнения (конфликт наследования)

**Ваш ответ:** B

### Уровень 5. NumPy

**Задание 19. Создание массивов и поэлементные операции**

1. Создайте одномерный массив NumPy из списка `[2, 5, 8, 11, 14, 17, 20]`.
2. Создайте двумерный массив нулей размером 3×4.
3. Создайте массив из 50 равномерно распределённых точек на отрезке [0, 10].
4. Для массива из пункта 1: умножьте каждый элемент на 3, прибавьте 10, вычислите квадратный корень каждого элемента. Выведите результаты.
5. Создайте два массива формы `(3, 1)` и `(1, 4)` и продемонстрируйте broadcasting при их сложении.

In [16]:
# Задание 19
import numpy as np

# 19.1
data = np.array([2, 5, 8, 11, 14, 17, 20])

# 19.2
np.zeros((3,4))

# 19.3
np.linspace(0,10,50)

# 19.4
data = (data * 3 + 10)**0.5
print(data)

# 19.5
# Посмотрел в интернете что такое broadcasting и как оно работает, чем то похоже на перемножение матриц разных размеров в matlab
x = np.random.random((3,1))
y = np.random.random((1,4))
xy = x*y
print(xy)


[4.         5.         5.83095189 6.55743852 7.21110255 7.81024968
 8.36660027]
[[0.05368057 0.02824699 0.0614138  0.01655247]
 [0.08621989 0.04536935 0.09864074 0.02658601]
 [0.20058291 0.10554775 0.22947891 0.06184998]]


**Задание 20. Индексация и фильтрация массивов**

Создайте двумерный массив 5×5 случайных целых чисел от 0 до 99 (для воспроизводимости используйте `seed(42)`).

Выполните:
1. Извлеките третью строку.
2. Извлеките второй столбец.
3. Извлеките подматрицу из строк 1–2 и столбцов 2–3.
4. Найдите и выведите все элементы, которые больше 50.
5. Замените все элементы меньше 20 на 0.

In [17]:
# Задание 20
import numpy as np
# для использования seed пришлось изучить документацию
np.random.seed(42)
random_array = np.random.randint(0, 99, (5, 5))
print(random_array)

# 20.1
thre_str = random_array[2]

# 20.2
second_colume = random_array[:, 1]

# 20.3
down_matrix = random_array[1:3, 2:4]

# 20.4
sorted_array = [random_array > 50] # Посмотрел в интернете

# 20.5
a = random_array.copy() 
a[a < 20] = 0 # Посмотрел в интернете как заменить необходимые элементы массива
print(a)


[[51 92 14 71 60]
 [20 82 86 74 74]
 [87 23  2 21 52]
 [ 1 87 29 37  1]
 [63 59 20 32 75]]
[[51 92  0 71 60]
 [20 82 86 74 74]
 [87 23  0 21 52]
 [ 0 87 29 37  0]
 [63 59 20 32 75]]


**Задание 21. Статистики и преобразование формы массивов**

1. Создайте двумерный массив 4×6 случайных чисел (от 0 до 1).
2. Вычислите среднее и стандартное отклонение по столбцам и по строкам отдельно.
3. Вычислите сумму всех элементов и сумму по каждой строке.
4. Создайте одномерный массив из 12 элементов и преобразуйте его в матрицы 3×4 и 4×3.
5. Транспонируйте матрицу 3×4 и убедитесь, что результат имеет форму 4×3.

In [18]:
# Задание 21
import numpy as np

np.random.seed(0)
matrix = np.random.rand(4, 5)
print(matrix)


[[0.5488135  0.71518937 0.60276338 0.54488318 0.4236548 ]
 [0.64589411 0.43758721 0.891773   0.96366276 0.38344152]
 [0.79172504 0.52889492 0.56804456 0.92559664 0.07103606]
 [0.0871293  0.0202184  0.83261985 0.77815675 0.87001215]]


### Уровень 6. Pandas

**Задание 22. Создание DataFrame и базовые операции**

Создайте DataFrame из следующего словаря:

```python
data = {
    "Имя": ["Алексей", "Мария", "Иван", "Елена", "Дмитрий", "Ольга"],
    "Возраст": [25, 30, 22, 35, 28, 26],
    "Город": ["Москва", "Казань", "Москва", "Новосибирск", "Казань", "Москва"],
    "Зарплата": [70000, 85000, 55000, 90000, 65000, 75000],
}
```

Выполните:
1. Выведите первые 3 строки таблицы.
2. Выведите столбец `"Зарплата"` отдельно.
3. Получите строку с порядковым номером 2.
4. Добавьте новый столбец `"Налог"`, равный 13% от зарплаты.
5. Добавьте столбец `"Зарплата_после_налога"` — разница между зарплатой и налогом.
6. Выведите итоговый DataFrame.

In [60]:
# Задание 22



import pandas as pd

data = {
    "Имя": ["Алексей", "Мария", "Иван", "Елена", "Дмитрий", "Ольга"],
    "Возраст": [25, 30, 22, 35, 28, 26],
    "Город": ["Москва", "Казань", "Москва", "Новосибирск", "Казань", "Москва"],
    "Зарплата": [70000, 85000, 55000, 90000, 65000, 75000],
}
# 22.1
frame = pd.DataFrame(data)
# print(frame[0:3])

# --- К сожалению я не помню работу с библиотекой pandas, написанный дальше код был с помощью интернета и мануала (без ИИ)
# 22.2
first_colume = frame['Имя']
print(first_colume)

# 22.3
frame.iloc[2]

# 22.4
frame['Tax'] = frame['Зарплата'] * 0.13

# 22.5
frame['Differet'] = frame['Зарплата'] - frame['Tax']

# 22.6
print(frame)

0    Алексей
1      Мария
2       Иван
3      Елена
4    Дмитрий
5      Ольга
Name: Имя, dtype: str
       Имя  Возраст        Город  Зарплата      Tax  Differet
0  Алексей       25       Москва     70000   9100.0   60900.0
1    Мария       30       Казань     85000  11050.0   73950.0
2     Иван       22       Москва     55000   7150.0   47850.0
3    Елена       35  Новосибирск     90000  11700.0   78300.0
4  Дмитрий       28       Казань     65000   8450.0   56550.0
5    Ольга       26       Москва     75000   9750.0   65250.0


**Задание 23. Фильтрация, сортировка и преобразование данных**

Используя DataFrame из предыдущего задания:

1. Отфильтруйте строки, где зарплата превышает 65000.
2. Отсортируйте DataFrame по возрасту в порядке убывания.
3. Создайте новый столбец `"Категория"`, значение которого зависит от возраста:
   - `"junior"` — если возраст < 25
   - `"middle"` — если возраст от 25 до 30 (включительно)
   - `"senior"` — если возраст > 30
4. Выведите результат.

In [65]:
# Задание 23

# --- К сожалению я не помню работу с библиотекой pandas, написанный дальше код был с помощью интернета и мануала (без ИИ)

# 23.1
filter_frame = frame[frame['Зарплата'] > 65000]
print(filter_frame)

# 23.2
year_frame = frame.sort_values('Возраст', ascending=False)
print(year_frame)

# 23.4
category = frame.copy()
category['Category'] = category['Возраст'].apply(lambda x: 'junior' if x < 25 else ('middle' if x <= 30 else 'senior'))
print(category)

       Имя  Возраст        Город  Зарплата      Tax  Differet
0  Алексей       25       Москва     70000   9100.0   60900.0
1    Мария       30       Казань     85000  11050.0   73950.0
3    Елена       35  Новосибирск     90000  11700.0   78300.0
5    Ольга       26       Москва     75000   9750.0   65250.0
       Имя  Возраст        Город  Зарплата      Tax  Differet
3    Елена       35  Новосибирск     90000  11700.0   78300.0
1    Мария       30       Казань     85000  11050.0   73950.0
4  Дмитрий       28       Казань     65000   8450.0   56550.0
5    Ольга       26       Москва     75000   9750.0   65250.0
0  Алексей       25       Москва     70000   9100.0   60900.0
2     Иван       22       Москва     55000   7150.0   47850.0
       Имя  Возраст        Город  Зарплата      Tax  Differet Category
0  Алексей       25       Москва     70000   9100.0   60900.0   middle
1    Мария       30       Казань     85000  11050.0   73950.0   middle
2     Иван       22       Москва     55000 

**Задание 24. Группировка и агрегация**

Используя DataFrame из задания 22:

1. Вычислите среднюю зарплату в каждом городе.
2. Подсчитайте количество сотрудников в каждом городе.
3. Для каждого города одновременно вычислите: минимальную, максимальную и среднюю зарплату, а также средний возраст.
4. Выведите все результаты.

In [ ]:
# Задание 24

# --- К сожалению я не помню работу с библиотекой pandas, написанный дальше код был с помощью интернета и мануала (без ИИ)

avarage_salary = frame.groupby('Город')['Зарплата'].mean()
print(avarage_salary)

user_city = frame.groupby('Город')['Имя'].count()
print(user_city)

max_salary = frame.groupby('Город')['Зарплата'].max()
min_salary = frame.groupby('Город')['Зарплата'].min()
avg_salary = frame.groupby('Город')['Зарплата'].mean()
avg_age = frame.groupby('Город')['Возраст'].mean()

print(max_salary, min_salary, avg_salary, avg_age, sep=('\n\n'))



Город
Казань         75000.000000
Москва         66666.666667
Новосибирск    90000.000000
Name: Зарплата, dtype: float64
Город
Казань         2
Москва         3
Новосибирск    1
Name: Имя, dtype: int64
Город
Казань         85000
Москва         75000
Новосибирск    90000
Name: Зарплата, dtype: int64

Город
Казань         65000
Москва         55000
Новосибирск    90000
Name: Зарплата, dtype: int64

Город
Казань         75000.000000
Москва         66666.666667
Новосибирск    90000.000000
Name: Зарплата, dtype: float64

Город
Казань         29.000000
Москва         24.333333
Новосибирск    35.000000
Name: Возраст, dtype: float64


### Уровень 7. Matplotlib

**Задание 25. Линейный график**

Постройте на одном графике функции `y = sin(x)` и `y = cos(x)` на интервале x от 0 до 2π:

1. Создайте массив `x` из 100 равномерно распределённых точек на отрезке [0, 2π].
2. Постройте обе функции на одних осях с разными цветами и стилями линий.
3. Добавьте заголовок: `"Тригонометрические функции"`.
4. Подпишите оси: `"x"` и `"y"`.
5. Добавьте легенду и сетку.

In [ ]:
# Задание 25
import numpy as np
import matplotlib.pyplot as plt

# --- Matplotlib не изучал


**Задание 26. Несколько графиков на одной фигуре**

Создайте фигуру с двумя подграфиками в одну строку:

**Левый подграфик (линейный график):**
- Постройте y = x² для x от -5 до 5.
- Заголовок: `"Парабола"`.

**Правый подграфик (столбчатая диаграмма):**
- Категории: `["A", "B", "C", "D", "E"]`.
- Значения: `[23, 45, 12, 36, 29]`.
- Заголовок: `"Категории"`.

Добавьте общий заголовок фигуры.

In [ ]:
# Задание 26
import numpy as np
import matplotlib.pyplot as plt

# --- Matplotlib не изучал


**Задание 27. Scatter-plot с цветовой шкалой**

1. Сгенерируйте 200 случайных точек `x` и `y` из нормального распределения.
2. Для каждой точки вычислите расстояние от начала координат — это будет определять цвет точки.
3. Размер каждой точки задайте случайным числом от 20 до 200.
4. Постройте точечный график, где цвет и размер точки отражают вычисленные значения.
5. Добавьте цветовую шкалу, заголовок и подписи осей.

In [ ]:
# Задание 27
import numpy as np
import matplotlib.pyplot as plt

array_new = np.random.seed(42)
print(array_new)

# --- Matplotlib не изучал


None


**Квиз 28. Python list vs NumPy array vs Pandas Series**

Какие из следующих утверждений **верны**?

- **A)** Python `list` может содержать элементы разных типов; `numpy.ndarray` требует однородности типов.
- **B)** Арифметические операции над `numpy.ndarray` выполняются поэлементно, а над `list` — нет (например, `[1, 2] + [3, 4]` даёт `[1, 2, 3, 4]`, а не `[4, 6]`).
- **C)** `pandas.Series` поддерживает именованный индекс, в то время как `list` и `ndarray` используют только целочисленные позиции.
- **D)** Все утверждения (A, B, C) верны.

**Ваш ответ:** A, B

---

## Завершение

Поздравляем! Вы завершили входное тестирование.

Сохраните ноутбук (`Ctrl+S`) и отправьте его преподавателю.

Результаты тестирования помогут адаптировать подачу материала курса под уровень группы. Не переживайте, если не смогли выполнить все задания — в ходе курса мы будем использовать Python постепенно, и у вас будет возможность восполнить пробелы.